/*
 * ExceptionDisplayDialog.java
 *
 * Created on 11.02.2010, 19:39:36
 */

package salssuite.util.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 * Display any exception. This dialog presents a short summary of the
 * exception and the full stack trace, as well as a customisable message. It
 * supports a timeout after which the dialog will automatically be disposed.
 * @author Jannis Limperg
 */
public class ExceptionDisplayDialog extends javax.swing.JDialog {

    private static final long serialVersionUID=1;

    /**
     * Standard constructor.
     * @param parent This dialog's parent frame.
     * @param modal Whether this dialog should be modal or not.
     * @param ex The exception to be displayed.
     * @param heading An optional heading to be displayed on top of the other
     * information.
     */
    public ExceptionDisplayDialog(java.awt.Frame parent, boolean modal, Exception
            ex, String heading) {
        super(parent, modal);
        initComponents();


        jTextArea1.setText(ex.getMessage());

        String stackTrace = "";
        for(StackTraceElement el : ex.getStackTrace()) {
            stackTrace += el.toString()+"\n";
        }

        jTextArea2.setText("JAVA EXCEPTION\n" +
                ex.getMessage()+"\n\n"+
                "STACK TRACE\n"+
                stackTrace);
        jButton2.setVisible(false);
        headingDisplay.setText(heading);

        setLocationRelativeTo(parent);
    }

    /**
     * Full constructor.
     * @param parent This dialog's parent frame.
     * @param modal Whether this dialog should be modal or not.
     * @param ex The exception to be displayed.
     * @param heading An optional heading which is displayed on top of the other
     * information.
     * @param timeout The number of seconds after which the dialog is disposed
     * automatically.
     */
    public ExceptionDisplayDialog(java.awt.Frame parent, boolean modal, Exception
            ex, String heading, int timeout) {
            this(parent, modal, ex, heading);

            secCount = timeout;
            jLabel1.setText("Automatisch schließen in "+secCount+" Sekunden.");

            time = new Timer(1000, new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    if(secCount == 0)
                        dispose();
                    else
                        secCount -= 1;

                    jLabel1.setText("Automatisch schließen in "+secCount+
                            " Sekunden.");
                }
            });
            time.start();
            jButton2.setVisible(true);
    }


    /** This method is called from within the constructor to
     * initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        headingDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fehler");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("Fehlerbeschreibung");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setRows(10);
        jTextArea2.setToolTipText("Genauere Beschreibung des Fehlers. Für Java-Kundige.");
        jScrollPane4.setViewportView(jTextArea2);

        jButton1.setText("Schließen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose(evt);
            }
        });

        jButton2.setText("Anhalten");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopDisposing(evt);
            }
        });

        headingDisplay.setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 535, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 535, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headingDisplay)
                        .addContainerGap(549, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(headingDisplay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel1))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dispose(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispose
        dispose();
    }//GEN-LAST:event_dispose

    private void stopDisposing(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopDisposing
        if(time == null)
            return;

        time.stop();
        jLabel1.setText(null);
    }//GEN-LAST:event_stopDisposing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headingDisplay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables


    //=================================OWN CODE=================================

    int secCount;
    Timer time;
}
